<div class="accordion-container">
    <h2 class="accordion-header">Titulo Contenido</h2>
    <div class="accordion-container">
        <p class="accordion-content">Contenido de la sección 1</p>
        <p class="accordion-content">Contenido de la sección 2</p>
        <p class="accordion-content">Contenido de la sección 3</p>
        <p class="accordion-content">Contenido de la sección 4</p>
        <p class="accordion-content">Contenido de la sección 5</p>
    </div>
</div>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Heinsohn_PageCustom::js/accordion.js') ?>" ></script>