<div class="accordion-container">
    <h2 class="accordion-header">Titulo Sidebar</h2>
    <div class="accordion-container">
        <p class="accordion-content">Contenido del Sidebar 1</p>
        <p class="accordion-content">Contenido del Sidebar 2</p>
        <p class="accordion-content">Contenido del Sidebar 3</p>
        <p class="accordion-content">Contenido del Sidebar 4</p>
        <p class="accordion-content">Contenido del Sidebar 5</p>
    </div>
</div>

<script type="text/javascript" src="<?= $block->getViewFileUrl('Heinsohn_PageCustom::js/accordion.js') ?>" ></script>
